import { useMemo, useState } from 'react';
import { AppHeader } from '../components/AppHeader';
import { useChild } from '../hooks/useChild';
import { useReportData } from '../hooks/useReportData';
import { colors, categoryColor, categoryColorLight } from '../theme';
import { todayDateString, addDays } from '../utils/date';

type RangeOption = '7' | '14' | '30';

const RANGE_LABELS: Record<RangeOption, string> = {
  '7': '7 Days',
  '14': '14 Days',
  '30': '30 Days',
};

const RATING_LABELS: Record<string, { label: string; emoji: string; color: string }> = {
  better_than_usual: { label: 'Better', emoji: '😊', color: colors.betterThanUsual },
  typical: { label: 'Typical', emoji: '😐', color: colors.typical },
  difficult: { label: 'Difficult', emoji: '😟', color: colors.difficult },
};

const CATEGORY_EMOJIS: Record<string, string> = {
  behavior: '⚡', emotion: '😊', food: '🍽️', medication: '💊',
  sleep: '😴', sensory: '🔮', transitions: '🔄', successes: '🌟',
  trigger: '⚠️', other: '📝',
};

function formatDateShort(dateStr: string): string {
  const d = new Date(dateStr + 'T00:00:00');
  return d.toLocaleDateString([], { month: 'short', day: 'numeric' });
}

function formatDateRange(start: string, end: string): string {
  const s = new Date(start + 'T00:00:00');
  const e = new Date(end + 'T00:00:00');
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' };
  return `${s.toLocaleDateString([], opts)} – ${e.toLocaleDateString([], opts)}`;
}

export default function Reports() {
  const { child } = useChild();
  const [range, setRange] = useState<RangeOption>('7');

  const today = todayDateString();
  const startDate = addDays(today, -parseInt(range) + 1);
  const { data, loading } = useReportData(startDate, today);

  const maxCategory = useMemo(() => {
    if (!data?.categoryBreakdown.length) return 0;
    return Math.max(...data.categoryBreakdown.map((c) => c.count));
  }, [data]);

  const maxDaily = useMemo(() => {
    if (!data?.dailyCounts.length) return 0;
    return Math.max(...data.dailyCounts.map((d) => d.count));
  }, [data]);

  const shareReport = async () => {
    if (!data || !child) return;
    const lines = [
      `OpenSpectrum Report — ${child.display_name}`,
      `Period: ${formatDateRange(startDate, today)}`,
      `Total Observations: ${data.totalCount}`,
      '',
      '--- Category Breakdown ---',
      ...data.categoryBreakdown.map(
        (c) => `${CATEGORY_EMOJIS[c.category] ?? '📝'} ${c.category}: ${c.count}`
      ),
      '',
      '--- Top Tags ---',
      ...data.topTags.map((t, i) => `${i + 1}. ${t.name} (${t.count})`),
      '',
      '--- Daily Reflections ---',
      ...data.reflections.map(
        (r) => `${RATING_LABELS[r.rating]?.emoji ?? '❓'} ${RATING_LABELS[r.rating]?.label ?? r.rating}: ${r.count} days`
      ),
      '',
      'Generated by OpenSpectrum',
    ];

    if (navigator.share) {
      await navigator.share({ text: lines.join('\n') });
    } else {
      await navigator.clipboard.writeText(lines.join('\n'));
      alert('Report copied to clipboard');
    }
  };

  return (
    <div className="flex flex-col h-full bg-white">
      <AppHeader searchQuery="" onSearchChange={() => {}} placeholder="Search coming soon" showHome={true} editable={false} />
      <div className="flex-1 overflow-y-auto p-4 pb-12 space-y-4">
        {/* Range selector */}
        <div className="flex gap-2">
          {(Object.keys(RANGE_LABELS) as RangeOption[]).map((opt) => (
            <button
              key={opt}
              onClick={() => setRange(opt)}
              className={`flex-1 py-2 rounded-[10px] text-center border text-sm font-semibold ${
                range === opt
                  ? 'bg-primary border-primary text-white'
                  : 'bg-surface border-border text-text-secondary'
              }`}
            >
              {RANGE_LABELS[opt]}
            </button>
          ))}
        </div>

        <p className="text-sm text-text-muted text-center">{formatDateRange(startDate, today)}</p>

        {loading ? (
          <div className="flex justify-center pt-24">
            <div className="w-8 h-8 border-[3px] border-primary border-t-transparent rounded-full animate-spin" />
          </div>
        ) : !data || data.totalCount === 0 ? (
          <div className="flex flex-col items-center pt-20 gap-2">
            <span className="text-5xl">📭</span>
            <span className="text-lg font-semibold text-text-primary">No observations in this period</span>
            <span className="text-base text-text-secondary">Start logging to see your report</span>
          </div>
        ) : (
          <>
            {/* Total count card */}
            <div className="bg-primary-light rounded-2xl p-6 text-center">
              <div className="text-[40px] font-bold text-primary">{data.totalCount}</div>
              <div className="text-base text-primary">Total Observations</div>
            </div>

            {/* Category breakdown */}
            <div>
              <h3 className="text-lg font-semibold text-text-primary mb-3">By Category</h3>
              {data.categoryBreakdown.map((cat) => (
                <div key={cat.category} className="flex items-center mb-2 gap-2">
                  <span className="text-sm text-text-primary w-[110px] capitalize">
                    {CATEGORY_EMOJIS[cat.category] ?? '📝'} {cat.category}
                  </span>
                  <div className="flex-1 h-4 bg-surface-alt rounded overflow-hidden">
                    <div
                      className="h-full rounded"
                      style={{
                        width: `${(cat.count / maxCategory) * 100}%`,
                        backgroundColor: categoryColor(cat.category),
                      }}
                    />
                  </div>
                  <span className="text-sm font-semibold w-[30px] text-right" style={{ color: categoryColor(cat.category) }}>
                    {cat.count}
                  </span>
                </div>
              ))}
            </div>

            {/* Daily log chart */}
            <div>
              <h3 className="text-lg font-semibold text-text-primary mb-3">Daily Activity</h3>
              <div className="flex items-end gap-0.5 h-[120px] pt-5">
                {data.dailyCounts.map((day) => (
                  <div key={day.date} className="flex-1 flex flex-col items-center justify-end">
                    <span className="text-xs text-text-muted mb-0.5">{day.count}</span>
                    <div
                      className="w-[70%] rounded-sm bg-primary"
                      style={{ height: maxDaily > 0 ? Math.max((day.count / maxDaily) * 80, 4) : 4 }}
                    />
                    <span className="text-[10px] text-text-muted mt-0.5">
                      {formatDateShort(day.date).split(' ')[1]}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Top tags */}
            {data.topTags.length > 0 && (
              <div>
                <h3 className="text-lg font-semibold text-text-primary mb-3">Top Tags</h3>
                <div className="flex flex-wrap gap-2">
                  {data.topTags.map((tag) => (
                    <div
                      key={tag.name}
                      className="flex items-center gap-1 py-1 px-3 rounded-full"
                      style={{ backgroundColor: categoryColorLight(tag.category, 0.15) }}
                    >
                      <span className="text-sm font-semibold" style={{ color: categoryColor(tag.category) }}>
                        {tag.name}
                      </span>
                      <span
                        className="rounded-full px-1.5 py-px text-xs font-bold text-white min-w-[20px] text-center"
                        style={{ backgroundColor: categoryColor(tag.category) }}
                      >
                        {tag.count}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Reflections */}
            {data.reflections.length > 0 && (
              <div>
                <h3 className="text-lg font-semibold text-text-primary mb-3">Daily Reflections</h3>
                <div className="flex gap-2">
                  {data.reflections.map((r) => {
                    const info = RATING_LABELS[r.rating];
                    return (
                      <div
                        key={r.rating}
                        className="flex-1 flex flex-col items-center p-3 rounded-[10px] bg-surface border"
                        style={{ borderColor: info?.color ?? colors.border }}
                      >
                        <span className="text-2xl">{info?.emoji ?? '❓'}</span>
                        <span className="text-[22px] font-semibold mt-1" style={{ color: info?.color ?? colors.text }}>
                          {r.count}
                        </span>
                        <span className="text-xs text-text-secondary">{info?.label ?? r.rating}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Share button */}
            <button
              onClick={shareReport}
              className="w-full bg-primary rounded-[10px] py-3 text-center mt-2"
            >
              <span className="text-base font-semibold text-white">Share Report</span>
            </button>
          </>
        )}
      </div>
    </div>
  );
}
