import React, { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppHeader } from '../../src/components/AppHeader';
import { useChild } from '../../src/hooks/useChild';
import { useReportData } from '../../src/hooks/useReportData';
import { colors, typography, spacing, radius, categoryColor, categoryColorLight } from '../../src/theme';
import { todayDateString, addDays } from '../../src/utils/date';

type RangeOption = '7' | '14' | '30';

const RANGE_LABELS: Record<RangeOption, string> = {
  '7': '7 Days',
  '14': '14 Days',
  '30': '30 Days',
};

const RATING_LABELS: Record<string, { label: string; emoji: string; color: string }> = {
  better_than_usual: { label: 'Better', emoji: '😊', color: colors.betterThanUsual },
  typical: { label: 'Typical', emoji: '😐', color: colors.typical },
  difficult: { label: 'Difficult', emoji: '😟', color: colors.difficult },
};

const CATEGORY_EMOJIS: Record<string, string> = {
  behavior: '⚡',
  emotion: '😊',
  food: '🍽️',
  medication: '💊',
  sleep: '😴',
  sensory: '🔮',
  transitions: '🔄',
  successes: '🌟',
  trigger: '⚠️',
  other: '📝',
};

function formatDateShort(dateStr: string): string {
  const d = new Date(dateStr + 'T00:00:00');
  return d.toLocaleDateString([], { month: 'short', day: 'numeric' });
}

function formatDateRange(start: string, end: string): string {
  const s = new Date(start + 'T00:00:00');
  const e = new Date(end + 'T00:00:00');
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' };
  return `${s.toLocaleDateString([], opts)} – ${e.toLocaleDateString([], opts)}`;
}

export default function ReportsScreen() {
  const { child } = useChild();
  const [range, setRange] = useState<RangeOption>('7');

  const today = todayDateString();
  const startDate = addDays(today, -parseInt(range) + 1);
  const { data, loading } = useReportData(startDate, today);

  const maxCategory = useMemo(() => {
    if (!data?.categoryBreakdown.length) return 0;
    return Math.max(...data.categoryBreakdown.map((c) => c.count));
  }, [data]);

  const maxDaily = useMemo(() => {
    if (!data?.dailyCounts.length) return 0;
    return Math.max(...data.dailyCounts.map((d) => d.count));
  }, [data]);

  const shareReport = async () => {
    if (!data || !child) return;
    const lines = [
      `OpenSpectrum Report — ${child.display_name}`,
      `Period: ${formatDateRange(startDate, today)}`,
      `Total Observations: ${data.totalCount}`,
      '',
      '--- Category Breakdown ---',
      ...data.categoryBreakdown.map(
        (c) => `${CATEGORY_EMOJIS[c.category] ?? '📝'} ${c.category}: ${c.count}`
      ),
      '',
      '--- Top Tags ---',
      ...data.topTags.map((t, i) => `${i + 1}. ${t.name} (${t.count})`),
      '',
      '--- Daily Reflections ---',
      ...data.reflections.map(
        (r) => `${RATING_LABELS[r.rating]?.emoji ?? '❓'} ${RATING_LABELS[r.rating]?.label ?? r.rating}: ${r.count} days`
      ),
      '',
      'Generated by OpenSpectrum',
    ];
    await Share.share({ message: lines.join('\n') });
  };

  return (
    <SafeAreaView style={styles.safeArea} edges={['top']}>
      <AppHeader
        searchQuery=""
        onSearchChange={() => {}}
        placeholder="Search coming soon"
        showHome={true}
        editable={false}
      />
      <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent}>
        {/* Range selector */}
        <View style={styles.rangeRow}>
          {(Object.keys(RANGE_LABELS) as RangeOption[]).map((opt) => (
            <Pressable
              key={opt}
              onPress={() => setRange(opt)}
              style={[styles.rangeBtn, range === opt && styles.rangeBtnActive]}
            >
              <Text style={[styles.rangeBtnText, range === opt && styles.rangeBtnTextActive]}>
                {RANGE_LABELS[opt]}
              </Text>
            </Pressable>
          ))}
        </View>

        <Text style={styles.dateRange}>{formatDateRange(startDate, today)}</Text>

        {loading ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color={colors.primary} />
          </View>
        ) : !data || data.totalCount === 0 ? (
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyEmoji}>📭</Text>
            <Text style={styles.emptyText}>No observations in this period</Text>
            <Text style={styles.emptySubtext}>Start logging to see your report</Text>
          </View>
        ) : (
          <>
            {/* Total count card */}
            <View style={styles.totalCard}>
              <Text style={styles.totalNumber}>{data.totalCount}</Text>
              <Text style={styles.totalLabel}>Total Observations</Text>
            </View>

            {/* Category breakdown */}
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>By Category</Text>
              {data.categoryBreakdown.map((cat) => (
                <View key={cat.category} style={styles.barRow}>
                  <Text style={styles.barLabel}>
                    {CATEGORY_EMOJIS[cat.category] ?? '📝'} {cat.category}
                  </Text>
                  <View style={styles.barTrack}>
                    <View
                      style={[
                        styles.barFill,
                        {
                          width: `${(cat.count / maxCategory) * 100}%`,
                          backgroundColor: categoryColor(cat.category),
                        },
                      ]}
                    />
                  </View>
                  <Text style={[styles.barCount, { color: categoryColor(cat.category) }]}>
                    {cat.count}
                  </Text>
                </View>
              ))}
            </View>

            {/* Daily log chart */}
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Daily Activity</Text>
              <View style={styles.dailyChart}>
                {data.dailyCounts.map((day) => (
                  <View key={day.date} style={styles.dailyBarCol}>
                    <Text style={styles.dailyCount}>{day.count}</Text>
                    <View
                      style={[
                        styles.dailyBar,
                        {
                          height: maxDaily > 0 ? Math.max((day.count / maxDaily) * 80, 4) : 4,
                          backgroundColor: colors.primary,
                        },
                      ]}
                    />
                    <Text style={styles.dailyLabel}>{formatDateShort(day.date).split(' ')[1]}</Text>
                  </View>
                ))}
              </View>
            </View>

            {/* Top tags */}
            {data.topTags.length > 0 && (
              <View style={styles.section}>
                <Text style={styles.sectionTitle}>Top Tags</Text>
                <View style={styles.tagList}>
                  {data.topTags.map((tag, i) => (
                    <View
                      key={tag.name}
                      style={[styles.tagChip, { backgroundColor: categoryColorLight(tag.category, 0.15) }]}
                    >
                      <Text style={[styles.tagText, { color: categoryColor(tag.category) }]}>
                        {tag.name}
                      </Text>
                      <View style={[styles.tagBadge, { backgroundColor: categoryColor(tag.category) }]}>
                        <Text style={styles.tagBadgeText}>{tag.count}</Text>
                      </View>
                    </View>
                  ))}
                </View>
              </View>
            )}

            {/* Reflections */}
            {data.reflections.length > 0 && (
              <View style={styles.section}>
                <Text style={styles.sectionTitle}>Daily Reflections</Text>
                <View style={styles.reflectionRow}>
                  {data.reflections.map((r) => {
                    const info = RATING_LABELS[r.rating];
                    return (
                      <View key={r.rating} style={[styles.reflectionCard, { borderColor: info?.color ?? colors.border }]}>
                        <Text style={styles.reflectionEmoji}>{info?.emoji ?? '❓'}</Text>
                        <Text style={[styles.reflectionCount, { color: info?.color ?? colors.text }]}>
                          {r.count}
                        </Text>
                        <Text style={styles.reflectionLabel}>{info?.label ?? r.rating}</Text>
                      </View>
                    );
                  })}
                </View>
              </View>
            )}

            {/* Share button */}
            <Pressable style={styles.shareBtn} onPress={shareReport}>
              <Text style={styles.shareBtnText}>Share Report</Text>
            </Pressable>
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.lg,
    paddingBottom: spacing.xxxl,
  },
  rangeRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  rangeBtn: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  rangeBtnActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  rangeBtnText: {
    ...typography.label,
    color: colors.textSecondary,
  },
  rangeBtnTextActive: {
    color: colors.white,
  },
  dateRange: {
    ...typography.bodySmall,
    color: colors.textMuted,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 100,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 80,
    gap: spacing.sm,
  },
  emptyEmoji: {
    fontSize: 48,
  },
  emptyText: {
    ...typography.h3,
    color: colors.text,
  },
  emptySubtext: {
    ...typography.body,
    color: colors.textSecondary,
  },
  totalCard: {
    backgroundColor: colors.primaryLight,
    borderRadius: radius.lg,
    padding: spacing.xl,
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  totalNumber: {
    fontSize: 40,
    fontWeight: '700',
    color: colors.primary,
  },
  totalLabel: {
    ...typography.body,
    color: colors.primary,
  },
  section: {
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    ...typography.h3,
    color: colors.text,
    marginBottom: spacing.md,
  },
  barRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
    gap: spacing.sm,
  },
  barLabel: {
    ...typography.bodySmall,
    color: colors.text,
    width: 110,
    textTransform: 'capitalize',
  },
  barTrack: {
    flex: 1,
    height: 16,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.sm,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    borderRadius: radius.sm,
  },
  barCount: {
    ...typography.label,
    width: 30,
    textAlign: 'right',
  },
  dailyChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
    height: 120,
    paddingTop: 20,
  },
  dailyBarCol: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  dailyBar: {
    width: '70%',
    borderRadius: 3,
    minHeight: 4,
  },
  dailyCount: {
    ...typography.caption,
    color: colors.textMuted,
    marginBottom: 2,
  },
  dailyLabel: {
    ...typography.caption,
    color: colors.textMuted,
    marginTop: 2,
    fontSize: 10,
  },
  tagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  tagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radius.full,
    gap: spacing.xs,
  },
  tagText: {
    ...typography.label,
  },
  tagBadge: {
    borderRadius: radius.full,
    paddingHorizontal: 6,
    paddingVertical: 1,
    minWidth: 20,
    alignItems: 'center',
  },
  tagBadgeText: {
    ...typography.caption,
    color: colors.white,
    fontWeight: '700',
  },
  reflectionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  reflectionCard: {
    flex: 1,
    alignItems: 'center',
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    backgroundColor: colors.surface,
  },
  reflectionEmoji: {
    fontSize: 24,
  },
  reflectionCount: {
    ...typography.h2,
    marginTop: spacing.xs,
  },
  reflectionLabel: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  shareBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  shareBtnText: {
    ...typography.button,
    color: colors.white,
  },
});
